services:
  - type: web
    name: gae-rj
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn core.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: SECRET_KEY
        value: c$ez_#gcl3o-tbdpyqj$st)ptu=8#!3s2xj-t*0k586daf%@$y
