services:
  - type: web
    name: gae-rj
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      python manage.py shell < create_superuser.py &&
      gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
