services:
  - type: web
    name: gae-rj
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      echo "from estrutura.models import Usuario; Usuario.objects.filter(username='joao.rafael').exists() or Usuario.objects.create_superuser('joao.rafael', 'admin@email.com', 'Zetraxa4@#')" | python manage.py shell
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
